In [ ]:
import numpy as np

# create a ary using numpy
# craete a !d array using numpy

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

In [ ]:
arr2=np.array([1,2,3,4,5])

arr2.reshape(1,5) # reshape the array to 1 row and 5 columns

In [ ]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
arr3.shape

In [ ]:
np.arange(0, 10, 2).reshape(5,1) # create an array with values from 1 to 10 with step of 2

In [ ]:
np.ones((3, 3)) # create a 3x3 array with all values as 1   

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print("addtion = ", arr1 + arr2) # add two arrays
print("subtraction = ", arr1 - arr2) # subtract two arrays
print("multiplication = ", arr1 * arr2) # multiply two arrays
print("division = ", arr1 / arr2) # divide two arrays

In [ ]:
# universal function÷//

arr1 = np.array([1, 2, 3, 4, 5])
# squre root
print("spure root = ", np.sqrt(arr1)) # square root of each element in the array

print(np.exp(arr1)) # exponential of each element in the array

print(np.sin(arr1))

print(np.log(arr1))

In [ ]:
# array licing and indexing

arr = np.array([[1, 2, 3, 4,5],[6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("Array: \n",arr)

In [23]:
arr[1:]= 100
print("Array after slicing: \n", arr)

Array after slicing: 
 [[  1   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [ ]:
# statistical functiond
# to have mean of end 0÷
